[build]
  publish = "frontend"

# Redirect “comodi” (opzionali) così puoi usare /room invece di /room.html
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/room"
  to = "/room.html"
  status = 200

[[redirects]]
  from = "/roll"
  to = "/roll.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/status"
  to = "/status.html"
  status = 200
